CREATE TABLE [dbo].[Customer] (
    [Id]                              INT IDENTITY (1, 1)	NOT NULL,
    [Name]                            NVARCHAR (1024)		NOT NULL,
    [Address]                         NVARCHAR (MAX)		NULL,
    [Telephone]                       NVARCHAR (1024)		NULL,
    [HomePage]                        NVARCHAR (1024)		NULL,
    [Owner]                           NVARCHAR (1024)		NULL,
    [Subsidiaries]                    NVARCHAR (MAX)		NULL,
    [CVR]                             NCHAR (10)			NULL,
    [Management]                      NVARCHAR (MAX)		NULL,
    [Responsible]                     NVARCHAR (MAX)		NULL,
    [Board]                           NVARCHAR (MAX)		NULL,
    [IndustrialClassification]        NVARCHAR (MAX)		NULL,
    [IsPBSPayment]                    BIT					NOT NULL,
    [IndustrialAssociationMembership] NVARCHAR (MAX)		NULL,
    [GroupSales]                      NVARCHAR (MAX)		NULL,
    [EmployeeCount]                   INT					NOT NULL,
	[Activities]                      NVARCHAR (MAX)		NULL,
    [CreatedOn]                       DATETIME				NULL,
    [CreatedBy]                       NVARCHAR (1024)		NULL,
    [ModifiedOn]                      DATETIME				NULL,
    [ModifiedBy]                      NVARCHAR (1024)		NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([Id] ASC)
);

