CREATE TABLE [dbo].[Customer] (
    [Id]                              INT IDENTITY (1, 1)	NOT NULL,
    [Name]                            NVARCHAR (1024)		NOT NULL,
    [Address]                         NVARCHAR (MAX)		NULL,
    [Telephone]                       NVARCHAR (1024)		NULL,
	[Email]                           NVARCHAR (1024)		NULL,
    [HomePage]                        NVARCHAR (1024)		NULL,
    [Subsidiaries]                    NVARCHAR (MAX)		NULL,
	[IndustrialClassification]        NVARCHAR (MAX)		NULL,
    [CVR]                             NCHAR (10)			NULL,
    [Responsible]                     NVARCHAR (1024)		NULL,
	[ResponsibleEmail]                NVARCHAR (1024)   	NULL,
	[ResponsibleTelephone]            NVARCHAR (1024)   	NULL,
    [IsPBSPayment]                    BIT					NOT NULL,
    [RegistrationNumber]              NVARCHAR (1024)		NULL,
	[AccountNumber]                   NVARCHAR (1024)		NULL,
	[MultiannualAgreement]			  INT					NOT NULL,
    [Forwards]                        INT					NOT NULL,
	[Activities]                      NVARCHAR (MAX)		NULL,
    [CreatedOn]                       DATETIME				NULL,
    [CreatedBy]                       NVARCHAR (1024)		NULL,
    [ModifiedOn]                      DATETIME				NULL,
    [ModifiedBy]                      NVARCHAR (1024)		NULL,
    CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED ([Id] ASC)
);

